services:
  app:
    build: .
    container_name: bun-app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN_SECONDS=${JWT_EXPIRES_IN_SECONDS}
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: bun-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
